// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenges.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const acceptChallenge = `-- name: AcceptChallenge :one
UPDATE challenges
SET status = 'ACCEPTED',
    opponent_id = $2,
    accepted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status = 'OPEN'
  AND acceptance_deadline > NOW()
  AND creator_id != $2
  AND NOT ($2 = ANY(COALESCE(rejected_by, '{}'::uuid[])))
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

type AcceptChallengeParams struct {
	ID         uuid.UUID     `json:"id"`
	OpponentID uuid.NullUUID `json:"opponent_id"`
}

func (q *Queries) AcceptChallenge(ctx context.Context, arg AcceptChallengeParams) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, acceptChallenge, arg.ID, arg.OpponentID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.OpponentID,
		&i.Type,
		&i.Game,
		&i.Status,
		&i.StakeAmount,
		&i.AcceptanceDeadline,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.MatchDeadline,
		&i.EndedAt,
		pq.Array(&i.RejectedBy),
		&i.CreatorStreamKey,
		&i.CreatorPlaybackID,
		&i.OpponentStreamKey,
		&i.OpponentPlaybackID,
		&i.CreatorAssetID,
		&i.OpponentAssetID,
		&i.CreatorReady,
		&i.OpponentReady,
		&i.AiWinnerID,
		&i.AiScore,
		&i.AiConfidence,
		&i.VerdictAt,
		&i.DisputeDeadline,
		&i.DisputedBy,
		&i.DisputeReason,
		&i.DisputedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addRejectedBy = `-- name: AddRejectedBy :one
UPDATE challenges
SET rejected_by = array_append(COALESCE(rejected_by, '{}'), $2),
    updated_at = NOW()
WHERE id = $1
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

type AddRejectedByParams struct {
	ID          uuid.UUID   `json:"id"`
	ArrayAppend interface{} `json:"array_append"`
}

func (q *Queries) AddRejectedBy(ctx context.Context, arg AddRejectedByParams) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, addRejectedBy, arg.ID, arg.ArrayAppend)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.OpponentID,
		&i.Type,
		&i.Game,
		&i.Status,
		&i.StakeAmount,
		&i.AcceptanceDeadline,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.MatchDeadline,
		&i.EndedAt,
		pq.Array(&i.RejectedBy),
		&i.CreatorStreamKey,
		&i.CreatorPlaybackID,
		&i.OpponentStreamKey,
		&i.OpponentPlaybackID,
		&i.CreatorAssetID,
		&i.OpponentAssetID,
		&i.CreatorReady,
		&i.OpponentReady,
		&i.AiWinnerID,
		&i.AiScore,
		&i.AiConfidence,
		&i.VerdictAt,
		&i.DisputeDeadline,
		&i.DisputedBy,
		&i.DisputeReason,
		&i.DisputedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const autoSubmitExpiredMatches = `-- name: AutoSubmitExpiredMatches :many
UPDATE challenges
SET status = 'AI_REVIEW', updated_at = NOW()
WHERE status = 'IN_PROGRESS'
  AND match_deadline < NOW()
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

func (q *Queries) AutoSubmitExpiredMatches(ctx context.Context) ([]Challenge, error) {
	rows, err := q.db.QueryContext(ctx, autoSubmitExpiredMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.OpponentID,
			&i.Type,
			&i.Game,
			&i.Status,
			&i.StakeAmount,
			&i.AcceptanceDeadline,
			&i.AcceptedAt,
			&i.StartedAt,
			&i.MatchDeadline,
			&i.EndedAt,
			pq.Array(&i.RejectedBy),
			&i.CreatorStreamKey,
			&i.CreatorPlaybackID,
			&i.OpponentStreamKey,
			&i.OpponentPlaybackID,
			&i.CreatorAssetID,
			&i.OpponentAssetID,
			&i.CreatorReady,
			&i.OpponentReady,
			&i.AiWinnerID,
			&i.AiScore,
			&i.AiConfidence,
			&i.VerdictAt,
			&i.DisputeDeadline,
			&i.DisputedBy,
			&i.DisputeReason,
			&i.DisputedAt,
			&i.ResolvedBy,
			&i.ResolutionNote,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelChallenge = `-- name: CancelChallenge :one
UPDATE challenges
SET status = 'CANCELLED', updated_at = NOW()
WHERE id = $1
  AND creator_id = $2
  AND status = 'OPEN'
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

type CancelChallengeParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) CancelChallenge(ctx context.Context, arg CancelChallengeParams) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, cancelChallenge, arg.ID, arg.CreatorID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.OpponentID,
		&i.Type,
		&i.Game,
		&i.Status,
		&i.StakeAmount,
		&i.AcceptanceDeadline,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.MatchDeadline,
		&i.EndedAt,
		pq.Array(&i.RejectedBy),
		&i.CreatorStreamKey,
		&i.CreatorPlaybackID,
		&i.OpponentStreamKey,
		&i.OpponentPlaybackID,
		&i.CreatorAssetID,
		&i.OpponentAssetID,
		&i.CreatorReady,
		&i.OpponentReady,
		&i.AiWinnerID,
		&i.AiScore,
		&i.AiConfidence,
		&i.VerdictAt,
		&i.DisputeDeadline,
		&i.DisputedBy,
		&i.DisputeReason,
		&i.DisputedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeChallenge = `-- name: CompleteChallenge :one
UPDATE challenges
SET status = 'COMPLETED', ended_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

func (q *Queries) CompleteChallenge(ctx context.Context, id uuid.UUID) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, completeChallenge, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.OpponentID,
		&i.Type,
		&i.Game,
		&i.Status,
		&i.StakeAmount,
		&i.AcceptanceDeadline,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.MatchDeadline,
		&i.EndedAt,
		pq.Array(&i.RejectedBy),
		&i.CreatorStreamKey,
		&i.CreatorPlaybackID,
		&i.OpponentStreamKey,
		&i.OpponentPlaybackID,
		&i.CreatorAssetID,
		&i.OpponentAssetID,
		&i.CreatorReady,
		&i.OpponentReady,
		&i.AiWinnerID,
		&i.AiScore,
		&i.AiConfidence,
		&i.VerdictAt,
		&i.DisputeDeadline,
		&i.DisputedBy,
		&i.DisputeReason,
		&i.DisputedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO challenges (creator_id, type, game, stake_amount, opponent_id, acceptance_deadline)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

type CreateChallengeParams struct {
	CreatorID          uuid.UUID     `json:"creator_id"`
	Type               ChallengeType `json:"type"`
	Game               ChallengeGame `json:"game"`
	StakeAmount        int64         `json:"stake_amount"`
	OpponentID         uuid.NullUUID `json:"opponent_id"`
	AcceptanceDeadline time.Time     `json:"acceptance_deadline"`
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, createChallenge,
		arg.CreatorID,
		arg.Type,
		arg.Game,
		arg.StakeAmount,
		arg.OpponentID,
		arg.AcceptanceDeadline,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.OpponentID,
		&i.Type,
		&i.Game,
		&i.Status,
		&i.StakeAmount,
		&i.AcceptanceDeadline,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.MatchDeadline,
		&i.EndedAt,
		pq.Array(&i.RejectedBy),
		&i.CreatorStreamKey,
		&i.CreatorPlaybackID,
		&i.OpponentStreamKey,
		&i.OpponentPlaybackID,
		&i.CreatorAssetID,
		&i.OpponentAssetID,
		&i.CreatorReady,
		&i.OpponentReady,
		&i.AiWinnerID,
		&i.AiScore,
		&i.AiConfidence,
		&i.VerdictAt,
		&i.DisputeDeadline,
		&i.DisputedBy,
		&i.DisputeReason,
		&i.DisputedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disputeChallenge = `-- name: DisputeChallenge :one
UPDATE challenges
SET status = 'DISPUTED',
    disputed_by = $2,
    dispute_reason = $3,
    disputed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status = 'VERDICT'
  AND dispute_deadline > NOW()
  AND (creator_id = $2 OR opponent_id = $2)
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

type DisputeChallengeParams struct {
	ID            uuid.UUID      `json:"id"`
	DisputedBy    uuid.NullUUID  `json:"disputed_by"`
	DisputeReason sql.NullString `json:"dispute_reason"`
}

func (q *Queries) DisputeChallenge(ctx context.Context, arg DisputeChallengeParams) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, disputeChallenge, arg.ID, arg.DisputedBy, arg.DisputeReason)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.OpponentID,
		&i.Type,
		&i.Game,
		&i.Status,
		&i.StakeAmount,
		&i.AcceptanceDeadline,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.MatchDeadline,
		&i.EndedAt,
		pq.Array(&i.RejectedBy),
		&i.CreatorStreamKey,
		&i.CreatorPlaybackID,
		&i.OpponentStreamKey,
		&i.OpponentPlaybackID,
		&i.CreatorAssetID,
		&i.OpponentAssetID,
		&i.CreatorReady,
		&i.OpponentReady,
		&i.AiWinnerID,
		&i.AiScore,
		&i.AiConfidence,
		&i.VerdictAt,
		&i.DisputeDeadline,
		&i.DisputedBy,
		&i.DisputeReason,
		&i.DisputedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireChallenges = `-- name: ExpireChallenges :many
UPDATE challenges
SET status = 'EXPIRED', updated_at = NOW()
WHERE status = 'OPEN'
  AND acceptance_deadline < NOW()
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

func (q *Queries) ExpireChallenges(ctx context.Context) ([]Challenge, error) {
	rows, err := q.db.QueryContext(ctx, expireChallenges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.OpponentID,
			&i.Type,
			&i.Game,
			&i.Status,
			&i.StakeAmount,
			&i.AcceptanceDeadline,
			&i.AcceptedAt,
			&i.StartedAt,
			&i.MatchDeadline,
			&i.EndedAt,
			pq.Array(&i.RejectedBy),
			&i.CreatorStreamKey,
			&i.CreatorPlaybackID,
			&i.OpponentStreamKey,
			&i.OpponentPlaybackID,
			&i.CreatorAssetID,
			&i.OpponentAssetID,
			&i.CreatorReady,
			&i.OpponentReady,
			&i.AiWinnerID,
			&i.AiScore,
			&i.AiConfidence,
			&i.VerdictAt,
			&i.DisputeDeadline,
			&i.DisputedBy,
			&i.DisputeReason,
			&i.DisputedAt,
			&i.ResolvedBy,
			&i.ResolutionNote,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChallengeByID = `-- name: GetChallengeByID :one
SELECT id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at FROM challenges WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChallengeByID(ctx context.Context, id uuid.UUID) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, getChallengeByID, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.OpponentID,
		&i.Type,
		&i.Game,
		&i.Status,
		&i.StakeAmount,
		&i.AcceptanceDeadline,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.MatchDeadline,
		&i.EndedAt,
		pq.Array(&i.RejectedBy),
		&i.CreatorStreamKey,
		&i.CreatorPlaybackID,
		&i.OpponentStreamKey,
		&i.OpponentPlaybackID,
		&i.CreatorAssetID,
		&i.OpponentAssetID,
		&i.CreatorReady,
		&i.OpponentReady,
		&i.AiWinnerID,
		&i.AiScore,
		&i.AiConfidence,
		&i.VerdictAt,
		&i.DisputeDeadline,
		&i.DisputedBy,
		&i.DisputeReason,
		&i.DisputedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMyChallenges = `-- name: GetMyChallenges :many
SELECT id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at FROM challenges
WHERE creator_id = $1 OR opponent_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetMyChallengesParams struct {
	CreatorID uuid.UUID `json:"creator_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) GetMyChallenges(ctx context.Context, arg GetMyChallengesParams) ([]Challenge, error) {
	rows, err := q.db.QueryContext(ctx, getMyChallenges, arg.CreatorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.OpponentID,
			&i.Type,
			&i.Game,
			&i.Status,
			&i.StakeAmount,
			&i.AcceptanceDeadline,
			&i.AcceptedAt,
			&i.StartedAt,
			&i.MatchDeadline,
			&i.EndedAt,
			pq.Array(&i.RejectedBy),
			&i.CreatorStreamKey,
			&i.CreatorPlaybackID,
			&i.OpponentStreamKey,
			&i.OpponentPlaybackID,
			&i.CreatorAssetID,
			&i.OpponentAssetID,
			&i.CreatorReady,
			&i.OpponentReady,
			&i.AiWinnerID,
			&i.AiScore,
			&i.AiConfidence,
			&i.VerdictAt,
			&i.DisputeDeadline,
			&i.DisputedBy,
			&i.DisputeReason,
			&i.DisputedAt,
			&i.ResolvedBy,
			&i.ResolutionNote,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenLobby = `-- name: GetOpenLobby :many
SELECT id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at FROM challenges
WHERE status = 'OPEN'
  AND acceptance_deadline > NOW()
  AND (
    type = 'PUBLIC'
    OR (type = 'FRIENDS' AND creator_id = ANY($1::uuid[]))
  )
  AND ($2::challenge_game IS NULL OR game = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetOpenLobbyParams struct {
	Column1 []uuid.UUID   `json:"column_1"`
	Column2 ChallengeGame `json:"column_2"`
	Limit   int32         `json:"limit"`
	Offset  int32         `json:"offset"`
}

func (q *Queries) GetOpenLobby(ctx context.Context, arg GetOpenLobbyParams) ([]Challenge, error) {
	rows, err := q.db.QueryContext(ctx, getOpenLobby,
		pq.Array(arg.Column1),
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.OpponentID,
			&i.Type,
			&i.Game,
			&i.Status,
			&i.StakeAmount,
			&i.AcceptanceDeadline,
			&i.AcceptedAt,
			&i.StartedAt,
			&i.MatchDeadline,
			&i.EndedAt,
			pq.Array(&i.RejectedBy),
			&i.CreatorStreamKey,
			&i.CreatorPlaybackID,
			&i.OpponentStreamKey,
			&i.OpponentPlaybackID,
			&i.CreatorAssetID,
			&i.OpponentAssetID,
			&i.CreatorReady,
			&i.OpponentReady,
			&i.AiWinnerID,
			&i.AiScore,
			&i.AiConfidence,
			&i.VerdictAt,
			&i.DisputeDeadline,
			&i.DisputedBy,
			&i.DisputeReason,
			&i.DisputedAt,
			&i.ResolvedBy,
			&i.ResolutionNote,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenChallenge = `-- name: ReopenChallenge :one
UPDATE challenges
SET type = $2,
    opponent_id = NULL,
    status = 'OPEN',
    acceptance_deadline = NOW() + INTERVAL '24 hours',
    accepted_at = NULL,
    updated_at = NOW()
WHERE id = $1 AND creator_id = $3 AND status = 'OPEN'
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

type ReopenChallengeParams struct {
	ID        uuid.UUID     `json:"id"`
	Type      ChallengeType `json:"type"`
	CreatorID uuid.UUID     `json:"creator_id"`
}

func (q *Queries) ReopenChallenge(ctx context.Context, arg ReopenChallengeParams) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, reopenChallenge, arg.ID, arg.Type, arg.CreatorID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.OpponentID,
		&i.Type,
		&i.Game,
		&i.Status,
		&i.StakeAmount,
		&i.AcceptanceDeadline,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.MatchDeadline,
		&i.EndedAt,
		pq.Array(&i.RejectedBy),
		&i.CreatorStreamKey,
		&i.CreatorPlaybackID,
		&i.OpponentStreamKey,
		&i.OpponentPlaybackID,
		&i.CreatorAssetID,
		&i.OpponentAssetID,
		&i.CreatorReady,
		&i.OpponentReady,
		&i.AiWinnerID,
		&i.AiScore,
		&i.AiConfidence,
		&i.VerdictAt,
		&i.DisputeDeadline,
		&i.DisputedBy,
		&i.DisputeReason,
		&i.DisputedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveDispute = `-- name: ResolveDispute :one
UPDATE challenges
SET status = $3,
    resolved_by = $2,
    resolution_note = $4,
    resolved_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND status = 'DISPUTED'
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

type ResolveDisputeParams struct {
	ID             uuid.UUID       `json:"id"`
	ResolvedBy     uuid.NullUUID   `json:"resolved_by"`
	Status         ChallengeStatus `json:"status"`
	ResolutionNote sql.NullString  `json:"resolution_note"`
}

func (q *Queries) ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, resolveDispute,
		arg.ID,
		arg.ResolvedBy,
		arg.Status,
		arg.ResolutionNote,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.OpponentID,
		&i.Type,
		&i.Game,
		&i.Status,
		&i.StakeAmount,
		&i.AcceptanceDeadline,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.MatchDeadline,
		&i.EndedAt,
		pq.Array(&i.RejectedBy),
		&i.CreatorStreamKey,
		&i.CreatorPlaybackID,
		&i.OpponentStreamKey,
		&i.OpponentPlaybackID,
		&i.CreatorAssetID,
		&i.OpponentAssetID,
		&i.CreatorReady,
		&i.OpponentReady,
		&i.AiWinnerID,
		&i.AiScore,
		&i.AiConfidence,
		&i.VerdictAt,
		&i.DisputeDeadline,
		&i.DisputedBy,
		&i.DisputeReason,
		&i.DisputedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCreatorAsset = `-- name: SetCreatorAsset :exec
UPDATE challenges SET creator_asset_id = $2, updated_at = NOW() WHERE id = $1
`

type SetCreatorAssetParams struct {
	ID             uuid.UUID      `json:"id"`
	CreatorAssetID sql.NullString `json:"creator_asset_id"`
}

func (q *Queries) SetCreatorAsset(ctx context.Context, arg SetCreatorAssetParams) error {
	_, err := q.db.ExecContext(ctx, setCreatorAsset, arg.ID, arg.CreatorAssetID)
	return err
}

const setCreatorReady = `-- name: SetCreatorReady :one
UPDATE challenges
SET creator_ready = TRUE, updated_at = NOW()
WHERE id = $1 AND creator_id = $2 AND status = 'ACCEPTED'
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

type SetCreatorReadyParams struct {
	ID        uuid.UUID `json:"id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) SetCreatorReady(ctx context.Context, arg SetCreatorReadyParams) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, setCreatorReady, arg.ID, arg.CreatorID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.OpponentID,
		&i.Type,
		&i.Game,
		&i.Status,
		&i.StakeAmount,
		&i.AcceptanceDeadline,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.MatchDeadline,
		&i.EndedAt,
		pq.Array(&i.RejectedBy),
		&i.CreatorStreamKey,
		&i.CreatorPlaybackID,
		&i.OpponentStreamKey,
		&i.OpponentPlaybackID,
		&i.CreatorAssetID,
		&i.OpponentAssetID,
		&i.CreatorReady,
		&i.OpponentReady,
		&i.AiWinnerID,
		&i.AiScore,
		&i.AiConfidence,
		&i.VerdictAt,
		&i.DisputeDeadline,
		&i.DisputedBy,
		&i.DisputeReason,
		&i.DisputedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setMuxStreams = `-- name: SetMuxStreams :one
UPDATE challenges
SET creator_stream_key  = $2,
    creator_playback_id = $3,
    opponent_stream_key = $4,
    opponent_playback_id = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

type SetMuxStreamsParams struct {
	ID                 uuid.UUID      `json:"id"`
	CreatorStreamKey   sql.NullString `json:"creator_stream_key"`
	CreatorPlaybackID  sql.NullString `json:"creator_playback_id"`
	OpponentStreamKey  sql.NullString `json:"opponent_stream_key"`
	OpponentPlaybackID sql.NullString `json:"opponent_playback_id"`
}

func (q *Queries) SetMuxStreams(ctx context.Context, arg SetMuxStreamsParams) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, setMuxStreams,
		arg.ID,
		arg.CreatorStreamKey,
		arg.CreatorPlaybackID,
		arg.OpponentStreamKey,
		arg.OpponentPlaybackID,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.OpponentID,
		&i.Type,
		&i.Game,
		&i.Status,
		&i.StakeAmount,
		&i.AcceptanceDeadline,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.MatchDeadline,
		&i.EndedAt,
		pq.Array(&i.RejectedBy),
		&i.CreatorStreamKey,
		&i.CreatorPlaybackID,
		&i.OpponentStreamKey,
		&i.OpponentPlaybackID,
		&i.CreatorAssetID,
		&i.OpponentAssetID,
		&i.CreatorReady,
		&i.OpponentReady,
		&i.AiWinnerID,
		&i.AiScore,
		&i.AiConfidence,
		&i.VerdictAt,
		&i.DisputeDeadline,
		&i.DisputedBy,
		&i.DisputeReason,
		&i.DisputedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setOpponentAsset = `-- name: SetOpponentAsset :exec
UPDATE challenges SET opponent_asset_id = $2, updated_at = NOW() WHERE id = $1
`

type SetOpponentAssetParams struct {
	ID              uuid.UUID      `json:"id"`
	OpponentAssetID sql.NullString `json:"opponent_asset_id"`
}

func (q *Queries) SetOpponentAsset(ctx context.Context, arg SetOpponentAssetParams) error {
	_, err := q.db.ExecContext(ctx, setOpponentAsset, arg.ID, arg.OpponentAssetID)
	return err
}

const setOpponentReady = `-- name: SetOpponentReady :one
UPDATE challenges
SET opponent_ready = TRUE, updated_at = NOW()
WHERE id = $1 AND opponent_id = $2 AND status = 'ACCEPTED'
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

type SetOpponentReadyParams struct {
	ID         uuid.UUID     `json:"id"`
	OpponentID uuid.NullUUID `json:"opponent_id"`
}

func (q *Queries) SetOpponentReady(ctx context.Context, arg SetOpponentReadyParams) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, setOpponentReady, arg.ID, arg.OpponentID)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.OpponentID,
		&i.Type,
		&i.Game,
		&i.Status,
		&i.StakeAmount,
		&i.AcceptanceDeadline,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.MatchDeadline,
		&i.EndedAt,
		pq.Array(&i.RejectedBy),
		&i.CreatorStreamKey,
		&i.CreatorPlaybackID,
		&i.OpponentStreamKey,
		&i.OpponentPlaybackID,
		&i.CreatorAssetID,
		&i.OpponentAssetID,
		&i.CreatorReady,
		&i.OpponentReady,
		&i.AiWinnerID,
		&i.AiScore,
		&i.AiConfidence,
		&i.VerdictAt,
		&i.DisputeDeadline,
		&i.DisputedBy,
		&i.DisputeReason,
		&i.DisputedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startChallenge = `-- name: StartChallenge :one
UPDATE challenges
SET status = 'IN_PROGRESS',
    started_at = NOW(),
    match_deadline = NOW() + INTERVAL '90 minutes',
    updated_at = NOW()
WHERE id = $1
  AND status = 'ACCEPTED'
  AND creator_ready = TRUE
  AND opponent_ready = TRUE
  AND creator_stream_key IS NOT NULL
  AND opponent_stream_key IS NOT NULL
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

func (q *Queries) StartChallenge(ctx context.Context, id uuid.UUID) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, startChallenge, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.OpponentID,
		&i.Type,
		&i.Game,
		&i.Status,
		&i.StakeAmount,
		&i.AcceptanceDeadline,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.MatchDeadline,
		&i.EndedAt,
		pq.Array(&i.RejectedBy),
		&i.CreatorStreamKey,
		&i.CreatorPlaybackID,
		&i.OpponentStreamKey,
		&i.OpponentPlaybackID,
		&i.CreatorAssetID,
		&i.OpponentAssetID,
		&i.CreatorReady,
		&i.OpponentReady,
		&i.AiWinnerID,
		&i.AiScore,
		&i.AiConfidence,
		&i.VerdictAt,
		&i.DisputeDeadline,
		&i.DisputedBy,
		&i.DisputeReason,
		&i.DisputedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitVerdict = `-- name: SubmitVerdict :one
UPDATE challenges
SET status = 'VERDICT',
    ai_winner_id = $2,
    ai_score = $3,
    ai_confidence = $4,
    verdict_at = NOW(),
    dispute_deadline = NOW() + INTERVAL '1 hour',
    updated_at = NOW()
WHERE id = $1
RETURNING id, creator_id, opponent_id, type, game, status, stake_amount, acceptance_deadline, accepted_at, started_at, match_deadline, ended_at, rejected_by, creator_stream_key, creator_playback_id, opponent_stream_key, opponent_playback_id, creator_asset_id, opponent_asset_id, creator_ready, opponent_ready, ai_winner_id, ai_score, ai_confidence, verdict_at, dispute_deadline, disputed_by, dispute_reason, disputed_at, resolved_by, resolution_note, resolved_at, created_at, updated_at
`

type SubmitVerdictParams struct {
	ID           uuid.UUID      `json:"id"`
	AiWinnerID   uuid.NullUUID  `json:"ai_winner_id"`
	AiScore      sql.NullString `json:"ai_score"`
	AiConfidence sql.NullString `json:"ai_confidence"`
}

func (q *Queries) SubmitVerdict(ctx context.Context, arg SubmitVerdictParams) (Challenge, error) {
	row := q.db.QueryRowContext(ctx, submitVerdict,
		arg.ID,
		arg.AiWinnerID,
		arg.AiScore,
		arg.AiConfidence,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.OpponentID,
		&i.Type,
		&i.Game,
		&i.Status,
		&i.StakeAmount,
		&i.AcceptanceDeadline,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.MatchDeadline,
		&i.EndedAt,
		pq.Array(&i.RejectedBy),
		&i.CreatorStreamKey,
		&i.CreatorPlaybackID,
		&i.OpponentStreamKey,
		&i.OpponentPlaybackID,
		&i.CreatorAssetID,
		&i.OpponentAssetID,
		&i.CreatorReady,
		&i.OpponentReady,
		&i.AiWinnerID,
		&i.AiScore,
		&i.AiConfidence,
		&i.VerdictAt,
		&i.DisputeDeadline,
		&i.DisputedBy,
		&i.DisputeReason,
		&i.DisputedAt,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
