// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friendships.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :one
UPDATE friendships
SET status = 'ACCEPTED', updated_at = NOW()
WHERE requester_id = $1 AND addressee_id = $2 AND status = 'PENDING'
RETURNING id, requester_id, addressee_id, status, created_at, updated_at
`

type AcceptFriendRequestParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	AddresseeID uuid.UUID `json:"addressee_id"`
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, acceptFriendRequest, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const declineFriendRequest = `-- name: DeclineFriendRequest :one
UPDATE friendships
SET status = 'DECLINED', updated_at = NOW()
WHERE requester_id = $1 AND addressee_id = $2 AND status = 'PENDING'
RETURNING id, requester_id, addressee_id, status, created_at, updated_at
`

type DeclineFriendRequestParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	AddresseeID uuid.UUID `json:"addressee_id"`
}

func (q *Queries) DeclineFriendRequest(ctx context.Context, arg DeclineFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, declineFriendRequest, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFriendIDs = `-- name: GetFriendIDs :many
SELECT (CASE
    WHEN requester_id = $1 THEN addressee_id
    ELSE requester_id
END)::uuid AS friend_id
FROM friendships
WHERE (requester_id = $1 OR addressee_id = $1)
  AND status = 'ACCEPTED'
`

func (q *Queries) GetFriendIDs(ctx context.Context, requesterID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getFriendIDs, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var friend_id uuid.UUID
		if err := rows.Scan(&friend_id); err != nil {
			return nil, err
		}
		items = append(items, friend_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriends = `-- name: GetFriends :many
SELECT
    u.id, u.username, u.first_name, u.last_name, u.avatar_url,
    u.game_preference, u.last_seen_at
FROM friendships f
JOIN users u ON (
    CASE WHEN f.requester_id = $1 THEN f.addressee_id ELSE f.requester_id END = u.id
)
WHERE (f.requester_id = $1 OR f.addressee_id = $1)
  AND f.status = 'ACCEPTED'
ORDER BY u.username ASC
`

type GetFriendsRow struct {
	ID             uuid.UUID      `json:"id"`
	Username       string         `json:"username"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	GamePreference GamePreference `json:"game_preference"`
	LastSeenAt     sql.NullTime   `json:"last_seen_at"`
}

func (q *Queries) GetFriends(ctx context.Context, requesterID uuid.UUID) ([]GetFriendsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriends, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendsRow
	for rows.Next() {
		var i GetFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
			&i.GamePreference,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendshipBetween = `-- name: GetFriendshipBetween :one
SELECT id, requester_id, addressee_id, status, created_at, updated_at FROM friendships
WHERE (requester_id = $1 AND addressee_id = $2)
   OR (requester_id = $2 AND addressee_id = $1)
LIMIT 1
`

type GetFriendshipBetweenParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	AddresseeID uuid.UUID `json:"addressee_id"`
}

func (q *Queries) GetFriendshipBetween(ctx context.Context, arg GetFriendshipBetweenParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, getFriendshipBetween, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingRequests = `-- name: GetPendingRequests :many
SELECT
    u.id, u.username, u.first_name, u.last_name, u.avatar_url,
    u.game_preference, u.last_seen_at,
    f.created_at AS requested_at
FROM friendships f
JOIN users u ON f.requester_id = u.id
WHERE f.addressee_id = $1 AND f.status = 'PENDING'
ORDER BY f.created_at DESC
`

type GetPendingRequestsRow struct {
	ID             uuid.UUID      `json:"id"`
	Username       string         `json:"username"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	GamePreference GamePreference `json:"game_preference"`
	LastSeenAt     sql.NullTime   `json:"last_seen_at"`
	RequestedAt    time.Time      `json:"requested_at"`
}

func (q *Queries) GetPendingRequests(ctx context.Context, addresseeID uuid.UUID) ([]GetPendingRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingRequests, addresseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingRequestsRow
	for rows.Next() {
		var i GetPendingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
			&i.GamePreference,
			&i.LastSeenAt,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFriend = `-- name: RemoveFriend :exec
DELETE FROM friendships
WHERE (requester_id = $1 AND addressee_id = $2)
   OR (requester_id = $2 AND addressee_id = $1)
`

type RemoveFriendParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	AddresseeID uuid.UUID `json:"addressee_id"`
}

func (q *Queries) RemoveFriend(ctx context.Context, arg RemoveFriendParams) error {
	_, err := q.db.ExecContext(ctx, removeFriend, arg.RequesterID, arg.AddresseeID)
	return err
}

const sendFriendRequest = `-- name: SendFriendRequest :one
INSERT INTO friendships (requester_id, addressee_id)
VALUES ($1, $2)
RETURNING id, requester_id, addressee_id, status, created_at, updated_at
`

type SendFriendRequestParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	AddresseeID uuid.UUID `json:"addressee_id"`
}

func (q *Queries) SendFriendRequest(ctx context.Context, arg SendFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, sendFriendRequest, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE users SET last_seen_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLastSeen, id)
	return err
}
