// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ChallengeGame string

const (
	ChallengeGameEFOOTBALL ChallengeGame = "EFOOTBALL"
	ChallengeGameDLS       ChallengeGame = "DLS"
)

func (e *ChallengeGame) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChallengeGame(s)
	case string:
		*e = ChallengeGame(s)
	default:
		return fmt.Errorf("unsupported scan type for ChallengeGame: %T", src)
	}
	return nil
}

type NullChallengeGame struct {
	ChallengeGame ChallengeGame `json:"challenge_game"`
	Valid         bool          `json:"valid"` // Valid is true if ChallengeGame is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChallengeGame) Scan(value interface{}) error {
	if value == nil {
		ns.ChallengeGame, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChallengeGame.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChallengeGame) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChallengeGame), nil
}

type ChallengeStatus string

const (
	ChallengeStatusOPEN          ChallengeStatus = "OPEN"
	ChallengeStatusACCEPTED      ChallengeStatus = "ACCEPTED"
	ChallengeStatusINPROGRESS    ChallengeStatus = "IN_PROGRESS"
	ChallengeStatusAIREVIEW      ChallengeStatus = "AI_REVIEW"
	ChallengeStatusVERDICT       ChallengeStatus = "VERDICT"
	ChallengeStatusCOMPLETED     ChallengeStatus = "COMPLETED"
	ChallengeStatusDISPUTED      ChallengeStatus = "DISPUTED"
	ChallengeStatusADMINRESOLVED ChallengeStatus = "ADMIN_RESOLVED"
	ChallengeStatusCANCELLED     ChallengeStatus = "CANCELLED"
	ChallengeStatusEXPIRED       ChallengeStatus = "EXPIRED"
	ChallengeStatusREFUNDED      ChallengeStatus = "REFUNDED"
)

func (e *ChallengeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChallengeStatus(s)
	case string:
		*e = ChallengeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChallengeStatus: %T", src)
	}
	return nil
}

type NullChallengeStatus struct {
	ChallengeStatus ChallengeStatus `json:"challenge_status"`
	Valid           bool            `json:"valid"` // Valid is true if ChallengeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChallengeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChallengeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChallengeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChallengeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChallengeStatus), nil
}

type ChallengeType string

const (
	ChallengeTypePUBLIC  ChallengeType = "PUBLIC"
	ChallengeTypeFRIENDS ChallengeType = "FRIENDS"
	ChallengeTypeDIRECT  ChallengeType = "DIRECT"
)

func (e *ChallengeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChallengeType(s)
	case string:
		*e = ChallengeType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChallengeType: %T", src)
	}
	return nil
}

type NullChallengeType struct {
	ChallengeType ChallengeType `json:"challenge_type"`
	Valid         bool          `json:"valid"` // Valid is true if ChallengeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChallengeType) Scan(value interface{}) error {
	if value == nil {
		ns.ChallengeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChallengeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChallengeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChallengeType), nil
}

type FriendshipStatus string

const (
	FriendshipStatusPENDING  FriendshipStatus = "PENDING"
	FriendshipStatusACCEPTED FriendshipStatus = "ACCEPTED"
	FriendshipStatusDECLINED FriendshipStatus = "DECLINED"
)

func (e *FriendshipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FriendshipStatus(s)
	case string:
		*e = FriendshipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FriendshipStatus: %T", src)
	}
	return nil
}

type NullFriendshipStatus struct {
	FriendshipStatus FriendshipStatus `json:"friendship_status"`
	Valid            bool             `json:"valid"` // Valid is true if FriendshipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFriendshipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FriendshipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FriendshipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFriendshipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FriendshipStatus), nil
}

type GamePreference string

const (
	GamePreferenceEFOOTBALL GamePreference = "EFOOTBALL"
	GamePreferenceDLS       GamePreference = "DLS"
	GamePreferenceBOTH      GamePreference = "BOTH"
)

func (e *GamePreference) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GamePreference(s)
	case string:
		*e = GamePreference(s)
	default:
		return fmt.Errorf("unsupported scan type for GamePreference: %T", src)
	}
	return nil
}

type NullGamePreference struct {
	GamePreference GamePreference `json:"game_preference"`
	Valid          bool           `json:"valid"` // Valid is true if GamePreference is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGamePreference) Scan(value interface{}) error {
	if value == nil {
		ns.GamePreference, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GamePreference.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGamePreference) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GamePreference), nil
}

type TransactionStatus string

const (
	TransactionStatusPENDING     TransactionStatus = "PENDING"
	TransactionStatusCOMPLETED   TransactionStatus = "COMPLETED"
	TransactionStatusFAILED      TransactionStatus = "FAILED"
	TransactionStatusUNDERREVIEW TransactionStatus = "UNDER_REVIEW"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus `json:"transaction_status"`
	Valid             bool              `json:"valid"` // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type TransactionType string

const (
	TransactionTypeDEPOSIT            TransactionType = "DEPOSIT"
	TransactionTypeWITHDRAWAL         TransactionType = "WITHDRAWAL"
	TransactionTypeCHALLENGESTAKE     TransactionType = "CHALLENGE_STAKE"
	TransactionTypeCHALLENGEREFUND    TransactionType = "CHALLENGE_REFUND"
	TransactionTypeCHALLENGEWINNINGS  TransactionType = "CHALLENGE_WINNINGS"
	TransactionTypePLATFORMFEE        TransactionType = "PLATFORM_FEE"
	TransactionTypeTOURNAMENTENTRY    TransactionType = "TOURNAMENT_ENTRY"
	TransactionTypeTOURNAMENTWINNINGS TransactionType = "TOURNAMENT_WINNINGS"
	TransactionTypeDISPUTEFREEZE      TransactionType = "DISPUTE_FREEZE"
	TransactionTypeADMINCREDIT        TransactionType = "ADMIN_CREDIT"
	TransactionTypeADMINDEBIT         TransactionType = "ADMIN_DEBIT"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type BankAccount struct {
	ID                    uuid.UUID `json:"id"`
	UserID                uuid.UUID `json:"user_id"`
	BankName              string    `json:"bank_name"`
	BankCode              string    `json:"bank_code"`
	AccountNumber         string    `json:"account_number"`
	AccountName           string    `json:"account_name"`
	PaystackRecipientCode string    `json:"paystack_recipient_code"`
	CreatedAt             time.Time `json:"created_at"`
}

type Challenge struct {
	ID                 uuid.UUID       `json:"id"`
	CreatorID          uuid.UUID       `json:"creator_id"`
	OpponentID         uuid.NullUUID   `json:"opponent_id"`
	Type               ChallengeType   `json:"type"`
	Game               ChallengeGame   `json:"game"`
	Status             ChallengeStatus `json:"status"`
	StakeAmount        int64           `json:"stake_amount"`
	AcceptanceDeadline time.Time       `json:"acceptance_deadline"`
	AcceptedAt         sql.NullTime    `json:"accepted_at"`
	StartedAt          sql.NullTime    `json:"started_at"`
	MatchDeadline      sql.NullTime    `json:"match_deadline"`
	EndedAt            sql.NullTime    `json:"ended_at"`
	RejectedBy         []uuid.UUID     `json:"rejected_by"`
	CreatorStreamKey   sql.NullString  `json:"creator_stream_key"`
	CreatorPlaybackID  sql.NullString  `json:"creator_playback_id"`
	OpponentStreamKey  sql.NullString  `json:"opponent_stream_key"`
	OpponentPlaybackID sql.NullString  `json:"opponent_playback_id"`
	CreatorAssetID     sql.NullString  `json:"creator_asset_id"`
	OpponentAssetID    sql.NullString  `json:"opponent_asset_id"`
	CreatorReady       bool            `json:"creator_ready"`
	OpponentReady      bool            `json:"opponent_ready"`
	AiWinnerID         uuid.NullUUID   `json:"ai_winner_id"`
	AiScore            sql.NullString  `json:"ai_score"`
	AiConfidence       sql.NullString  `json:"ai_confidence"`
	VerdictAt          sql.NullTime    `json:"verdict_at"`
	DisputeDeadline    sql.NullTime    `json:"dispute_deadline"`
	DisputedBy         uuid.NullUUID   `json:"disputed_by"`
	DisputeReason      sql.NullString  `json:"dispute_reason"`
	DisputedAt         sql.NullTime    `json:"disputed_at"`
	ResolvedBy         uuid.NullUUID   `json:"resolved_by"`
	ResolutionNote     sql.NullString  `json:"resolution_note"`
	ResolvedAt         sql.NullTime    `json:"resolved_at"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type Friendship struct {
	ID          uuid.UUID        `json:"id"`
	RequesterID uuid.UUID        `json:"requester_id"`
	AddresseeID uuid.UUID        `json:"addressee_id"`
	Status      FriendshipStatus `json:"status"`
	CreatedAt   time.Time        `json:"created_at"`
	UpdatedAt   time.Time        `json:"updated_at"`
}

type Transaction struct {
	ID        uuid.UUID             `json:"id"`
	UserID    uuid.UUID             `json:"user_id"`
	Type      TransactionType       `json:"type"`
	Amount    int64                 `json:"amount"`
	Status    TransactionStatus     `json:"status"`
	Reference string                `json:"reference"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt time.Time             `json:"created_at"`
	UpdatedAt time.Time             `json:"updated_at"`
}

type User struct {
	ID                  uuid.UUID      `json:"id"`
	FirstName           string         `json:"first_name"`
	LastName            string         `json:"last_name"`
	Username            string         `json:"username"`
	Email               string         `json:"email"`
	PasswordHash        sql.NullString `json:"password_hash"`
	GoogleID            sql.NullString `json:"google_id"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	EmailVerified       bool           `json:"email_verified"`
	OtpCode             sql.NullString `json:"otp_code"`
	OtpExpiresAt        sql.NullTime   `json:"otp_expires_at"`
	ResetToken          sql.NullString `json:"reset_token"`
	ResetTokenExpiresAt sql.NullTime   `json:"reset_token_expires_at"`
	AvatarUrl           sql.NullString `json:"avatar_url"`
	Bio                 sql.NullString `json:"bio"`
	GamePreference      GamePreference `json:"game_preference"`
	LastSeenAt          sql.NullTime   `json:"last_seen_at"`
}

type Wallet struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	AvailableBalance int64     `json:"available_balance"`
	LockedBalance    int64     `json:"locked_balance"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}
