// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_tokens.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const deletePushToken = `-- name: DeletePushToken :exec
DELETE FROM push_tokens WHERE user_id = $1 AND token = $2
`

type DeletePushTokenParams struct {
	UserID uuid.UUID `json:"user_id"`
	Token  string    `json:"token"`
}

func (q *Queries) DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error {
	_, err := q.db.ExecContext(ctx, deletePushToken, arg.UserID, arg.Token)
	return err
}

const getPushTokensForUser = `-- name: GetPushTokensForUser :many
SELECT token FROM push_tokens WHERE user_id = $1
`

func (q *Queries) GetPushTokensForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPushTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPushTokensForUsers = `-- name: GetPushTokensForUsers :many
SELECT token FROM push_tokens WHERE user_id = ANY($1::uuid[])
`

func (q *Queries) GetPushTokensForUsers(ctx context.Context, dollar_1 []uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPushTokensForUsers, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerPushToken = `-- name: RegisterPushToken :exec
INSERT INTO push_tokens (user_id, token)
VALUES ($1, $2)
ON CONFLICT (user_id, token) DO NOTHING
`

type RegisterPushTokenParams struct {
	UserID uuid.UUID `json:"user_id"`
	Token  string    `json:"token"`
}

func (q *Queries) RegisterPushToken(ctx context.Context, arg RegisterPushTokenParams) error {
	_, err := q.db.ExecContext(ctx, registerPushToken, arg.UserID, arg.Token)
	return err
}
