// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWallet(ctx context.Context, userID uuid.UUID) (Wallet, error)
	CreditAvailable(ctx context.Context, arg CreditAvailableParams) (Wallet, error)
	DebitAvailable(ctx context.Context, arg DebitAvailableParams) (Wallet, error)
	DeductLocked(ctx context.Context, arg DeductLockedParams) (Wallet, error)
	GetBankAccount(ctx context.Context, userID uuid.UUID) (BankAccount, error)
	GetTransactionByReference(ctx context.Context, reference string) (Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetWalletByUserID(ctx context.Context, userID uuid.UUID) (Wallet, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	LockFunds(ctx context.Context, arg LockFundsParams) (Wallet, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) (User, error)
	SaveBankAccount(ctx context.Context, arg SaveBankAccountParams) (BankAccount, error)
	SetEmailVerified(ctx context.Context, id uuid.UUID) error
	SetOTP(ctx context.Context, arg SetOTPParams) error
	SetResetToken(ctx context.Context, arg SetResetTokenParams) error
	UnlockFunds(ctx context.Context, arg UnlockFundsParams) (Wallet, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error)
	UsernameExists(ctx context.Context, username string) (bool, error)
	VerifyEmailOTP(ctx context.Context, arg VerifyEmailOTPParams) (User, error)
	VerifyResetOTP(ctx context.Context, arg VerifyResetOTPParams) (User, error)
}

var _ Querier = (*Queries)(nil)
