// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptChallenge(ctx context.Context, arg AcceptChallengeParams) (Challenge, error)
	AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) (Friendship, error)
	AddRejectedBy(ctx context.Context, arg AddRejectedByParams) (Challenge, error)
	AutoSubmitExpiredMatches(ctx context.Context) ([]Challenge, error)
	CancelChallenge(ctx context.Context, arg CancelChallengeParams) (Challenge, error)
	CompleteChallenge(ctx context.Context, id uuid.UUID) (Challenge, error)
	CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error)
	CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWallet(ctx context.Context, userID uuid.UUID) (Wallet, error)
	CreditAvailable(ctx context.Context, arg CreditAvailableParams) (Wallet, error)
	DebitAvailable(ctx context.Context, arg DebitAvailableParams) (Wallet, error)
	DeclineFriendRequest(ctx context.Context, arg DeclineFriendRequestParams) (Friendship, error)
	DeductLocked(ctx context.Context, arg DeductLockedParams) (Wallet, error)
	DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error
	DisputeChallenge(ctx context.Context, arg DisputeChallengeParams) (Challenge, error)
	ExpireChallenges(ctx context.Context) ([]Challenge, error)
	GetActiveChallenge(ctx context.Context, creatorID uuid.UUID) (GetActiveChallengeRow, error)
	GetBankAccount(ctx context.Context, userID uuid.UUID) (BankAccount, error)
	GetChallengeByID(ctx context.Context, id uuid.UUID) (Challenge, error)
	GetFriendIDs(ctx context.Context, requesterID uuid.UUID) ([]uuid.UUID, error)
	GetFriends(ctx context.Context, requesterID uuid.UUID) ([]GetFriendsRow, error)
	GetFriendshipBetween(ctx context.Context, arg GetFriendshipBetweenParams) (Friendship, error)
	GetMyChallenges(ctx context.Context, arg GetMyChallengesParams) ([]Challenge, error)
	GetOpenLobby(ctx context.Context, arg GetOpenLobbyParams) ([]Challenge, error)
	GetPendingRequests(ctx context.Context, addresseeID uuid.UUID) ([]GetPendingRequestsRow, error)
	GetPushTokensForUser(ctx context.Context, userID uuid.UUID) ([]string, error)
	GetPushTokensForUsers(ctx context.Context, dollar_1 []uuid.UUID) ([]string, error)
	GetTransactionByReference(ctx context.Context, reference string) (Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetWalletByUserID(ctx context.Context, userID uuid.UUID) (Wallet, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	LockFunds(ctx context.Context, arg LockFundsParams) (Wallet, error)
	RegisterPushToken(ctx context.Context, arg RegisterPushTokenParams) error
	RemoveFriend(ctx context.Context, arg RemoveFriendParams) error
	ReopenChallenge(ctx context.Context, arg ReopenChallengeParams) (Challenge, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) (User, error)
	ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (Challenge, error)
	SaveBankAccount(ctx context.Context, arg SaveBankAccountParams) (BankAccount, error)
	SendFriendRequest(ctx context.Context, arg SendFriendRequestParams) (Friendship, error)
	SetCreatorAsset(ctx context.Context, arg SetCreatorAssetParams) error
	SetCreatorReady(ctx context.Context, arg SetCreatorReadyParams) (Challenge, error)
	SetEmailVerified(ctx context.Context, id uuid.UUID) error
	SetMuxStreams(ctx context.Context, arg SetMuxStreamsParams) (Challenge, error)
	SetOTP(ctx context.Context, arg SetOTPParams) error
	SetOpponentAsset(ctx context.Context, arg SetOpponentAssetParams) error
	SetOpponentReady(ctx context.Context, arg SetOpponentReadyParams) (Challenge, error)
	SetResetToken(ctx context.Context, arg SetResetTokenParams) error
	StartChallenge(ctx context.Context, id uuid.UUID) (Challenge, error)
	SubmitVerdict(ctx context.Context, arg SubmitVerdictParams) (Challenge, error)
	UnlockFunds(ctx context.Context, arg UnlockFundsParams) (Wallet, error)
	UpdateLastSeen(ctx context.Context, id uuid.UUID) error
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error)
	UsernameExists(ctx context.Context, username string) (bool, error)
	VerifyEmailOTP(ctx context.Context, arg VerifyEmailOTPParams) (User, error)
	VerifyResetOTP(ctx context.Context, arg VerifyResetOTPParams) (User, error)
}

var _ Querier = (*Queries)(nil)
