// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) FROM transactions
WHERE user_id = $1
  AND (CAST($2 AS TEXT) = '' OR type = $2::transaction_type)
  AND ($3::timestamptz = '0001-01-01' OR created_at >= $3)
  AND ($4::timestamptz = '0001-01-01' OR created_at <= $4)
`

type CountTransactionsParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 string    `json:"column_2"`
	Column3 time.Time `json:"column_3"`
	Column4 time.Time `json:"column_4"`
}

func (q *Queries) CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactions,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, type, amount, status, reference, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, amount, status, reference, metadata, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID    uuid.UUID             `json:"user_id"`
	Type      TransactionType       `json:"type"`
	Amount    int64                 `json:"amount"`
	Status    TransactionStatus     `json:"status"`
	Reference string                `json:"reference"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.Status,
		arg.Reference,
		arg.Metadata,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Status,
		&i.Reference,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id) VALUES ($1) RETURNING id, user_id, available_balance, locked_balance, created_at, updated_at
`

func (q *Queries) CreateWallet(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, createWallet, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AvailableBalance,
		&i.LockedBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const creditAvailable = `-- name: CreditAvailable :one
UPDATE wallets
SET available_balance = available_balance + $2, updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, available_balance, locked_balance, created_at, updated_at
`

type CreditAvailableParams struct {
	UserID           uuid.UUID `json:"user_id"`
	AvailableBalance int64     `json:"available_balance"`
}

func (q *Queries) CreditAvailable(ctx context.Context, arg CreditAvailableParams) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, creditAvailable, arg.UserID, arg.AvailableBalance)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AvailableBalance,
		&i.LockedBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const debitAvailable = `-- name: DebitAvailable :one
UPDATE wallets
SET available_balance = available_balance - $2, updated_at = NOW()
WHERE user_id = $1 AND available_balance >= $2
RETURNING id, user_id, available_balance, locked_balance, created_at, updated_at
`

type DebitAvailableParams struct {
	UserID           uuid.UUID `json:"user_id"`
	AvailableBalance int64     `json:"available_balance"`
}

func (q *Queries) DebitAvailable(ctx context.Context, arg DebitAvailableParams) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, debitAvailable, arg.UserID, arg.AvailableBalance)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AvailableBalance,
		&i.LockedBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deductLocked = `-- name: DeductLocked :one
UPDATE wallets
SET locked_balance = locked_balance - $2, updated_at = NOW()
WHERE user_id = $1 AND locked_balance >= $2
RETURNING id, user_id, available_balance, locked_balance, created_at, updated_at
`

type DeductLockedParams struct {
	UserID        uuid.UUID `json:"user_id"`
	LockedBalance int64     `json:"locked_balance"`
}

func (q *Queries) DeductLocked(ctx context.Context, arg DeductLockedParams) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, deductLocked, arg.UserID, arg.LockedBalance)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AvailableBalance,
		&i.LockedBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBankAccount = `-- name: GetBankAccount :one
SELECT id, user_id, bank_name, bank_code, account_number, account_name, paystack_recipient_code, created_at FROM bank_accounts WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetBankAccount(ctx context.Context, userID uuid.UUID) (BankAccount, error) {
	row := q.db.QueryRowContext(ctx, getBankAccount, userID)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BankName,
		&i.BankCode,
		&i.AccountNumber,
		&i.AccountName,
		&i.PaystackRecipientCode,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByReference = `-- name: GetTransactionByReference :one
SELECT id, user_id, type, amount, status, reference, metadata, created_at, updated_at FROM transactions WHERE reference = $1 LIMIT 1
`

func (q *Queries) GetTransactionByReference(ctx context.Context, reference string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByReference, reference)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Status,
		&i.Reference,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByUserID = `-- name: GetWalletByUserID :one
SELECT id, user_id, available_balance, locked_balance, created_at, updated_at FROM wallets WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetWalletByUserID(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, getWalletByUserID, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AvailableBalance,
		&i.LockedBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, type, amount, status, reference, metadata, created_at, updated_at FROM transactions
WHERE user_id = $1
  AND (CAST($2 AS TEXT) = '' OR type = $2::transaction_type)
  AND ($3::timestamptz = '0001-01-01' OR created_at >= $3)
  AND ($4::timestamptz = '0001-01-01' OR created_at <= $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListTransactionsParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 string    `json:"column_2"`
	Column3 time.Time `json:"column_3"`
	Column4 time.Time `json:"column_4"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.Status,
			&i.Reference,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFunds = `-- name: LockFunds :one
UPDATE wallets
SET available_balance = available_balance - $2,
    locked_balance = locked_balance + $2,
    updated_at = NOW()
WHERE user_id = $1 AND available_balance >= $2
RETURNING id, user_id, available_balance, locked_balance, created_at, updated_at
`

type LockFundsParams struct {
	UserID           uuid.UUID `json:"user_id"`
	AvailableBalance int64     `json:"available_balance"`
}

func (q *Queries) LockFunds(ctx context.Context, arg LockFundsParams) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, lockFunds, arg.UserID, arg.AvailableBalance)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AvailableBalance,
		&i.LockedBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveBankAccount = `-- name: SaveBankAccount :one
INSERT INTO bank_accounts (user_id, bank_name, bank_code, account_number, account_name, paystack_recipient_code)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE
SET bank_name = EXCLUDED.bank_name,
    bank_code = EXCLUDED.bank_code,
    account_number = EXCLUDED.account_number,
    account_name = EXCLUDED.account_name,
    paystack_recipient_code = EXCLUDED.paystack_recipient_code
RETURNING id, user_id, bank_name, bank_code, account_number, account_name, paystack_recipient_code, created_at
`

type SaveBankAccountParams struct {
	UserID                uuid.UUID `json:"user_id"`
	BankName              string    `json:"bank_name"`
	BankCode              string    `json:"bank_code"`
	AccountNumber         string    `json:"account_number"`
	AccountName           string    `json:"account_name"`
	PaystackRecipientCode string    `json:"paystack_recipient_code"`
}

func (q *Queries) SaveBankAccount(ctx context.Context, arg SaveBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRowContext(ctx, saveBankAccount,
		arg.UserID,
		arg.BankName,
		arg.BankCode,
		arg.AccountNumber,
		arg.AccountName,
		arg.PaystackRecipientCode,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BankName,
		&i.BankCode,
		&i.AccountNumber,
		&i.AccountName,
		&i.PaystackRecipientCode,
		&i.CreatedAt,
	)
	return i, err
}

const unlockFunds = `-- name: UnlockFunds :one
UPDATE wallets
SET locked_balance = locked_balance - $2,
    available_balance = available_balance + $2,
    updated_at = NOW()
WHERE user_id = $1 AND locked_balance >= $2
RETURNING id, user_id, available_balance, locked_balance, created_at, updated_at
`

type UnlockFundsParams struct {
	UserID        uuid.UUID `json:"user_id"`
	LockedBalance int64     `json:"locked_balance"`
}

func (q *Queries) UnlockFunds(ctx context.Context, arg UnlockFundsParams) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, unlockFunds, arg.UserID, arg.LockedBalance)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AvailableBalance,
		&i.LockedBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, user_id, type, amount, status, reference, metadata, created_at, updated_at
`

type UpdateTransactionStatusParams struct {
	ID     uuid.UUID         `json:"id"`
	Status TransactionStatus `json:"status"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionStatus, arg.ID, arg.Status)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Status,
		&i.Reference,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
